# Generated by Django 5.1.1 on 2024-09-26 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oculto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arma', models.CharField(max_length=45, null=True)),
                ('ropa', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('plataforma', models.CharField(max_length=45, null=True)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('url_pagina', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('numero', models.IntegerField(null=True)),
                ('dni', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=45, null=True)),
                ('contraseña', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasarela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=45, null=True)),
                ('total', models.FloatField(null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria')),
                ('juego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.carrito')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('pais', models.CharField(max_length=45, null=True)),
                ('apellido', models.CharField(max_length=45, null=True)),
                ('tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tarjeta')),
                ('validacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.validacion')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
