# Generated by Django 5.0.7 on 2024-12-05 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('numero', models.IntegerField(null=True)),
                ('dni', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=45, null=True)),
                ('contraseña', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('pais', models.CharField(max_length=45, null=True)),
                ('apellido', models.CharField(max_length=45, null=True)),
                ('tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tarjeta')),
                ('validacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.validacion')),
            ],
        ),
    ]
