# Generated by Django 5.1.1 on 2024-10-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_producto_precio_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='ropa',
            new_name='armadura',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
