# Generated by Django 5.0.7 on 2024-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_categoria_arma_remove_categoria_armadura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacion',
            name='correo',
            field=models.EmailField(max_length=45, null=True),
        ),
    ]
