# Generated by Django 5.0.7 on 2024-11-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
