# Generated by Django 5.1.1 on 2024-10-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0003_rename_ropa_categoria_armadura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='arma',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='armadura',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('arma', 'Arma'), ('armadura', 'Armadura')], default='arma', max_length=10),
        ),
    ]
